@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456",
    "teste": "teste"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/abc

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "teste teste",
    "email": "user@gmail.com",
    "password": "123456"
}