@baseUrl = http://localhost:3000

@jwtToken = {{authLogin.response.body.accessToken}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "joao@gmail.com",
    "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Marcos",
    "email": "joao@gmail.com",
    "password": "123456"
}

### Update User
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Marcos",
    "email": "marcos@gmail.com"
}

### Update User password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword": "123456",
    "newPassword": "1234567"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Create post owned
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "DELETE Tiutlo pddddost",
    "excerpt": "Excertsssso",
    "content": "Contenido",
    "coverImageUrl": "http://localhost"
}

### Read one post owned
# @name readOnePostOwned
GET {{baseUrl}}/post/me/0b1bcc55-bb8d-48f7-bb71-c00b8342d7f9
Authorization: Bearer {{jwtToken}}

### Read all posts owned
# @name readAllPostsOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{jwtToken}}

### Update post owned
# @name updatePostOwned
PATCH {{baseUrl}}/post/me/8933eb8e-9d28-4f81-adef-fb8c2c8972e7
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "NOVO - Titulo",
    "excerpt": "NOVO - Expect",
    "content": "NOVO - Contenido",
    "published": true
}

### Delete post owned
# @name deletePostOwned
DELETE {{baseUrl}}/post/me/0b1bcc55-bb8d-48f7-bb71-c00b8342d7f9
Authorization: Bearer {{jwtToken}}

### Read all post public
# @name readAllPostPublic
GET {{baseUrl}}/post/

### Read one post public
# @name readOnePostPublic
GET {{baseUrl}}/post/tiutlo-pddddost-obfsn0

### Upload Image
# @name uploadImage
POST {{baseUrl}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ../dev/imagens/image.png
------BryenFormBoundary--

### Read Image
# @name ReadImage
GET http://localhost:3000/uploads/2026-09-04/1788493857374-p9m08o.png