@baseUrl = http://localhost:3000

@jwtToken = {{authLogin.response.body.accessToken}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "joao@gmail.com",
    "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### Create User
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Marcos",
    "email": "joao@gmail.com",
    "password": "123456"
}

### Update User
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Marcos",
    "email": "marcos@gmail.com"
}

### Update User password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword": "123456",
    "newPassword": "1234567"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Delete one user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Create post owned
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "Tiutlo pddddost",
    "excerpt": "Excertsssso",
    "content": "Contenido",
    "coverImageUrl": "http://localhost"
}

### Read one post owned
# @name readOnePostOwned
GET {{baseUrl}}/post/me/30a688ec-8ee2-433b-aa48-c595409501e6
Authorization: Bearer {{jwtToken}}

### Read all posts owned
# @name readAllPostsOwned
GET {{baseUrl}}/post/me
Authorization: Bearer {{jwtToken}}

### Update post owned
# @name updatePostOwned
PATCH {{baseUrl}}/post/me/8933eb8e-9d28-4f81-adef-fb8c2c8972e7
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "NOVO - Titulo",
    "excerpt": "NOVO - Expect",
    "content": "NOVO - Contenido",
    "published": true
}